// Testimonial mock data
export const testimonialMockData = [
    {
        id: 1,
        name: 'Mark Smith',
        role: 'Travel Enthusiast',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 5,
        text: 'Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC.',
    },
    {
        id: 2,
        name: 'Elena Rostova',
        role: 'Product Designer',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 4,
        text: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
    },
    {
        id: 3,
        name: 'John Doe',
        role: 'Software Engineer',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 5,
        text: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.',
    },
    {
        id: 4,
        name: 'Jane Dow',
        role: 'QA Analyst',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 1,
        text: 'Extremely disappointing experience.',
    },
    {
        id: 5,
        name: 'Zero Star Tester',
        role: 'Reviewer',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 0,
        text: 'Testing how the UI handles a zero-star or unrated review calculation.',
    },
    {
        id: 6,
        name: 'Overenthusiastic User',
        role: 'VIP Client',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 6,
        text: 'Testing component resilience against ratings exceeding the expected 5-star max.',
    },
    {
        id: 7,
        name: 'Hubert Blaine Wolfeschlegelsteinhaus',
        role: 'Chief Executive Officer & Principal',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 4,
        text: 'Testing component resilience against ratings exceeding the expected 5-star max',
    },
    {
        id: 8,
        name: 'Li',
        role: 'Dev',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 3,
        text: 'OK.',
    },
    {
        id: 9,
        name: 'Sarah Jenkins',
        role: 'Content Specialist',
        avatar: '/assets/images/testimonial-vr-girl.webp',
        stars: 5,
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor',
    },
];
